### ISSUE TITLE
Connect Tokens to Ballots

### ISSUE THREAD

**Issue by LeoTuet** [LeoTuet/backend-we-want-to-sleep#53]
A token should be connected to a ballot in order to prevent using a token for a different ballot

The vote endpoint should then only create a vote when the token ballot and the vote ballot are the same

**Comment by 94726** [comment]
No, tokens are not bound to ballots at all.
As our plan was to use the tokens as way to authenticate our schools students.
If we end up having another ballot, we would just reuse the tokens because re-sending them would be too much of an effort.

Optionally we have the possibility to invalidate tokens.
